# Generated by Django 4.1.3 on 2023-01-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pinterest', '0002_pinterest_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pinterest/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
